---
# Create the config file for galicaster
- name: "Creating the config file"
  template: src="conf.ini" dest=/etc/galicaster/conf.ini owner={{ galicaster.user }} group={{ galicaster.group }} mode=0644
  tags:
    - galicaster-conf
    - galicaster

# Adding profiles defined in config
- name: "Adding extra profiles to capture agent"
  copy: src=../../../files/profiles/{{ item }} dest=/etc/galicaster/profiles/{{ item }}.ini owner=icto group=icto mode=0644
  when: galicaster.profiles is defined
  with_items: galicaster.profiles
  tags:
    - galicaster-conf
    - galicaster