---
# Create the config file for galicaster
- name: "Creating the config file"
  template: src="conf.ini" dest=/etc/galicaster/conf.ini owner={{ ansible_user }} group={{ ansible_user }} mode=0644
  when: galicaster.version == 1
  tags:
    - galicaster-conf
    - galicaster

# Create the config file for galicaster
- name: "Creating the config file"
  template: src="conf-v2.ini" dest=/etc/galicaster/conf.ini owner={{ ansible_user }} group={{ ansible_user }} mode=0644
  when: galicaster.version == 2
  tags:
    - galicaster-conf
    - galicaster

# Adding profiles defined in config
- name: "Adding extra profiles to capture agent"
  copy: src=../../../files/profiles/{{ item }} dest=/etc/galicaster/profiles/{{ item }}.ini owner={{ ansible_user }} group={{ ansible_user }} mode=0644
  when: galicaster.profiles is defined
  with_items: '{{ galicaster.profiles }}'
  tags:
    - galicaster-conf
    - galicaster
