---
# Download galicaster installation package
- name: "Checkout Galicaster code"
  get_url: url={{ galicaster_package }} force=yes dest=/tmp/galicaster.deb
  tags:
    - galicaster-install
    - galicaster

# Install deb package
- name: "Installing galicaster deb package"
  command: /usr/bin/dpkg --force-confold --install /tmp/galicaster.deb
  tags:
    - galicaster-install
    - galicaster
